apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "6"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: loki
    targetRevision: "*"
    helm:
      releaseName: loki
      valueFiles: []
      values: |
        deploymentMode: SingleBinary
        loki:
          auth_enabled: false
          commonConfig:
            replication_factor: 1
          storage:
            type: filesystem
          limits_config:
            retention_period: 720h
        singleBinary:
          replicas: 1
          persistence:
            enabled: true
            storageClass: hcloud-volumes
            size: 50Gi
        gateway:
          enabled: false
        backend:
          replicas: 0
        read:
          replicas: 0
        write:
          replicas: 0
        monitoring:
          selfMonitoring:
            enabled: false
            grafanaAgent:
              installOperator: false
          lokiCanary:
            enabled: false
        test:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: promtail
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "7"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: promtail
    targetRevision: "*"
    helm:
      releaseName: promtail
      values: |
        config:
          clients:
            - url: http://loki.logging.svc.cluster.local:3100/loki/api/v1/push
        tolerations:
          - key: node-role.kubernetes.io/control-plane
            operator: Exists
            effect: NoSchedule
        serviceMonitor:
          enabled: true
          namespace: monitoring
  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
