sonar.projectKey=VollcomDigital_hetzner-k8s-boilerplate
sonar.organization=vollcomdigital
sonar.projectName=hetzner-k8s-boilerplate
sonar.projectVersion=1.0

sonar.sources=terraform,kubernetes,scripts
sonar.inclusions=**/*.tf,**/*.tftpl,**/*.yaml,**/*.yml,**/*.sh
sonar.exclusions=**/.terraform/**,**/vendor/**,**/*.md,**/*.json

sonar.sourceEncoding=UTF-8
